nickname=
manifestUrl=http://localhost:3000/manifest
yandexDiskPublicUrl=https://disk.yandex.ru/d/UTf9nb2ZDDlJ0A
backendUrl=http://localhost:3000
gameDir=${user.home}/.tactical-launcher/game
javaPath=
serverHost=deluxewarfare.sosal.today
serverPort=25565
autoJoinServer=true
discordAuthEnabled=false
backendAuthEnabled=false
skinSystemEnabled=true
launcherSessionToken=
discordUsername=
